name: check_pull_request

on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm i
      - run: npm run lint
        working-directory: .
        env:
          BASE: ${{github.base_ref}}
          HEAD: ${{github.head_ref}}
